language: python

python:
 - "3.6"

before_install:
 - python --version
 - pip install -U pip
 - pip install -U pytest
 - pip install -U codecov
 - pip install -U pytest-cov
 - pip install -U setuptools

install: 
  - pip install -r requirements.txt
  - pip install -e .

script: pytest

after_success:
  - codecov

