site_name: LeAB Documentation
use_directory_urls: false
site_url: https://tlentali.github.io/leab/
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python

nav:
  - Home: index.md
  - Reference:
      - leAverage: reference/leAverage.md
      - leSuccess: reference/leSuccess.md
      - leSample: reference/leSample.md