name: Python Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout le code
      uses: actions/checkout@v3

    - name: Installer uv
      run: |
        curl -Ls https://astral.sh/uv/install.sh | bash
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Créer l’environnement virtuel avec uv
      run: uv venv

    - name: Activer le venv et installer les dépendances
      run: |
        source .venv/bin/activate
        uv pip install -r <(uv pip compile -g dev pyproject.toml)

    - name: Lancer les tests
      run: |
        source .venv/bin/activate
        pytest