name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install tools
      run: |
        python -m pip install --upgrade pip
        pip install bumpver build twine

    - name: Determine version bump type
      id: version
      run: |
        git fetch --tags
        LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "Last commit: $LAST_COMMIT_MESSAGE"

        if [[ "$LAST_COMMIT_MESSAGE" == *#major* ]]; then
          echo "bump=major" >> $GITHUB_OUTPUT
        elif [[ "$LAST_COMMIT_MESSAGE" == *#minor* ]]; then
          echo "bump=minor" >> $GITHUB_OUTPUT
        else
          echo "bump=patch" >> $GITHUB_OUTPUT
        fi

    - name: Bump version
      run: |
        bumpver update --${{ steps.version.outputs.bump }}

    - name: Commit bumped version
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "chore: bump version [skip ci]"
        git push

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m build
        twine upload dist/*
